apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "apisix-ingress-controller-manager.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.deployment.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "apisix-ingress-controller-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.deployment.podAnnotations }}
        {{- range $key, $value := $.Values.deployment.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      labels:
        {{- include "apisix-ingress-controller-manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        volumeMounts:
        - name: {{ .Release.Name }}-ingress-config
          mountPath: /app/conf/config.yaml
          subPath: config.yaml
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          {{- toYaml .Values.deployment.podSecurityContext | nindent 10 }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- tpl (. | toYaml) $ | nindent 8 }}
      {{- end }}
      volumes:
      - name: {{ .Release.Name }}-ingress-config
        configMap:
          name: {{ .Release.Name }}-ingress-config
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ .Release.Name }}
      terminationGracePeriodSeconds: 10
