apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "apisix-ingress-controller-manager.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
   {{- include "apisix-ingress-controller-manager.selectorLabels" . | nindent 4 }}
