// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	"context"

	v2 "github.com/apache/apisix-ingress-controller/api/v2"
	scheme "github.com/apache/apisix-ingress-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ApisixGlobalRulesGetter has a method to return a ApisixGlobalRuleInterface.
// A group's client should implement this interface.
type ApisixGlobalRulesGetter interface {
	ApisixGlobalRules(namespace string) ApisixGlobalRuleInterface
}

// ApisixGlobalRuleInterface has methods to work with ApisixGlobalRule resources.
type ApisixGlobalRuleInterface interface {
	Create(ctx context.Context, apisixGlobalRule *v2.ApisixGlobalRule, opts v1.CreateOptions) (*v2.ApisixGlobalRule, error)
	Update(ctx context.Context, apisixGlobalRule *v2.ApisixGlobalRule, opts v1.UpdateOptions) (*v2.ApisixGlobalRule, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, apisixGlobalRule *v2.ApisixGlobalRule, opts v1.UpdateOptions) (*v2.ApisixGlobalRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.ApisixGlobalRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2.ApisixGlobalRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.ApisixGlobalRule, err error)
	ApisixGlobalRuleExpansion
}

// apisixGlobalRules implements ApisixGlobalRuleInterface
type apisixGlobalRules struct {
	*gentype.ClientWithList[*v2.ApisixGlobalRule, *v2.ApisixGlobalRuleList]
}

// newApisixGlobalRules returns a ApisixGlobalRules
func newApisixGlobalRules(c *ApisixV2Client, namespace string) *apisixGlobalRules {
	return &apisixGlobalRules{
		gentype.NewClientWithList[*v2.ApisixGlobalRule, *v2.ApisixGlobalRuleList](
			"apisixglobalrules",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v2.ApisixGlobalRule { return &v2.ApisixGlobalRule{} },
			func() *v2.ApisixGlobalRuleList { return &v2.ApisixGlobalRuleList{} }),
	}
}
