# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# permissions for end users to edit gatewayproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gatewayproxy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apisix-ingress-controller
    app.kubernetes.io/part-of: apisix-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: gatewayproxy-editor-role
rules:
- apiGroups:
  - apisix.apache.org
  resources:
  - gatewayproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apisix.apache.org
  resources:
  - gatewayproxies/status
  verbs:
  - get
