// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/apache/apisix-ingress-controller/api/v1alpha1"
	scheme "github.com/apache/apisix-ingress-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BackendTrafficPoliciesGetter has a method to return a BackendTrafficPolicyInterface.
// A group's client should implement this interface.
type BackendTrafficPoliciesGetter interface {
	BackendTrafficPolicies(namespace string) BackendTrafficPolicyInterface
}

// BackendTrafficPolicyInterface has methods to work with BackendTrafficPolicy resources.
type BackendTrafficPolicyInterface interface {
	Create(ctx context.Context, backendTrafficPolicy *v1alpha1.BackendTrafficPolicy, opts v1.CreateOptions) (*v1alpha1.BackendTrafficPolicy, error)
	Update(ctx context.Context, backendTrafficPolicy *v1alpha1.BackendTrafficPolicy, opts v1.UpdateOptions) (*v1alpha1.BackendTrafficPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, backendTrafficPolicy *v1alpha1.BackendTrafficPolicy, opts v1.UpdateOptions) (*v1alpha1.BackendTrafficPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BackendTrafficPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BackendTrafficPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BackendTrafficPolicy, err error)
	BackendTrafficPolicyExpansion
}

// backendTrafficPolicies implements BackendTrafficPolicyInterface
type backendTrafficPolicies struct {
	*gentype.ClientWithList[*v1alpha1.BackendTrafficPolicy, *v1alpha1.BackendTrafficPolicyList]
}

// newBackendTrafficPolicies returns a BackendTrafficPolicies
func newBackendTrafficPolicies(c *ApisixV1alpha1Client, namespace string) *backendTrafficPolicies {
	return &backendTrafficPolicies{
		gentype.NewClientWithList[*v1alpha1.BackendTrafficPolicy, *v1alpha1.BackendTrafficPolicyList](
			"backendtrafficpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.BackendTrafficPolicy { return &v1alpha1.BackendTrafficPolicy{} },
			func() *v1alpha1.BackendTrafficPolicyList { return &v1alpha1.BackendTrafficPolicyList{} }),
	}
}
