- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/authParameter/properties/hmacAuth/properties/value/required
  value: ["secret_key"]
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/authParameter/properties/hmacAuth/properties/value/oneOf
  value:
    - required: ["key_id", "secret_key"]
    - required: ["access_key", "secret_key"]
