apiVersion: apisix.apache.org/v1alpha1
kind: BackendTrafficPolicy
metadata:
  labels:
    app.kubernetes.io/name: apisix-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: backendtrafficpolicy-sample
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: httpbin
  scheme: http
  retries: 2
  loadbalancer:
    type: roundrobin
  timeout:
    connect: 5s
    read: 10s
    send: 10s
