apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
  labels:
    app.kubernetes.io/name: apisix-ingress-controller
    app.kubernetes.io/managed-by: kustomize
  name: apisixglobalrule-sample
spec:
  ingressClassName: apisix
  plugins:
    - name: prometheus
      enable: true
      config:
        prefer_name: true
