#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# commit to be tagged for new release
commit = "HEAD"

# project_name is used to refer to the project in the notes
project_name = "apisix-ingress-controller"

# github_repo is the github project, only github is currently supported
github_repo = "apache/apisix-ingress-controller"

# match_deps is a pattern to determine which dependencies should be included
# as part of this release. The changelog will also include changes for these
# dependencies based on the change in the dependency's version.
match_deps = "^github.com/(apache/[a-zA-Z0-9-]+)$"

# previous release of this project for determining changes
previous = "2.0.0-rc2"

# pre_release is whether to include a disclaimer about being a pre-release
pre_release = false

# preface is the description of the release which precedes the author list
# and changelog. This description could include highlights as well as any
# description of changes. Use markdown formatting.
preface = """\
This is a release candidate (RC) version.

## Highlights

### Features

* feat: support custom metrics [#2480](https://github.com/apache/apisix-ingress-controller/pull/2480)  
* feat: support event triggered synchronization [#2478](https://github.com/apache/apisix-ingress-controller/pull/2478)

### Bugfixes

* fix: route names with the same prefix were mistakenly deleted [#2472](https://github.com/apache/apisix-ingress-controller/pull/2472)  
* fix: should not return when service type is ExternalName [#2468](https://github.com/apache/apisix-ingress-controller/pull/2468)  
* fix: remove duplicate sync func [#2476](https://github.com/apache/apisix-ingress-controller/pull/2476)  
* fix: full sync during restart results in loss of dataplane traffic [#2489](https://github.com/apache/apisix-ingress-controller/pull/2489)

"""
