#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# commit to be tagged for new release
commit = "HEAD"

# project_name is used to refer to the project in the notes
project_name = "apisix-ingress-controller"

# github_repo is the github project, only github is currently supported
github_repo = "apache/apisix-ingress-controller"

# match_deps is a pattern to determine which dependencies should be included
# as part of this release. The changelog will also include changes for these
# dependencies based on the change in the dependency's version.
match_deps = "^github.com/(apache/[a-zA-Z0-9-]+)$"

# previous release of this project for determining changes
previous = "2.0.0-rc1"

# pre_release is whether to include a disclaimer about being a pre-release
pre_release = false

# preface is the description of the release which precedes the author list
# and changelog. This description could include highlights as well as any
# description of changes. Use markdown formatting.
preface = """\
This is a Patch version release.

## Highlights

### Features

* feat: support gatewayproxy controller to discovery of dataplane endpoints [#2444](https://github.com/apache/apisix-ingress-controller/pull/2444)
* feat: add synchronization status to CRD [#2460](https://github.com/apache/apisix-ingress-controller/pull/2460)

### Bugfix

* fix: should not contain plaintext token in log message [#2462](https://github.com/apache/apisix-ingress-controller/pull/2462)
* fix: add more event filter across controllers [#2449](https://github.com/apache/apisix-ingress-controller/pull/2449)
* fix: a failing endpoint shouldn't affect others [#2452](https://github.com/apache/apisix-ingress-controller/pull/2452)
* fix: Add provider endpoints to translate context [#2442](https://github.com/apache/apisix-ingress-controller/pull/2442)
* fix: config not provided should not be retried [#2454](https://github.com/apache/apisix-ingress-controller/pull/2454)
* fix: apisixroute backend service reference to apisixupstream [#2453](https://github.com/apache/apisix-ingress-controller/pull/2453)
* fix: adc backend server on different mode [#2455](https://github.com/apache/apisix-ingress-controller/pull/2455)
* fix: support filter endpoint when translate backend ref [#2451](https://github.com/apache/apisix-ingress-controller/pull/2451)
* fix: reduce the complexity of calculating route priority [#2459](https://github.com/apache/apisix-ingress-controller/pull/2459)

"""
