{
 "title": "Apache APISIX Ingress Controller",
 "description": "Ingress Controller of Apache APISIX",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "resource", "query": { "query": "label_values(resource)" } },
   { "name": "operation", "query": { "query": "label_values(operation)" } }
  ]
 },
 "panels": [
  { "title": "APISIX Ingress controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Is Leader",
   "type": "stat",
   "description": "Whether the role of controller instance is leader",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apisix_ingress_controller_is_leader"
    }
   ]
  },
  {
   "title": "Cache Sync Operations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(apisix_ingress_controller_cache_sync_total[5m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Sync Operations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(apisix_ingress_controller_sync_operation_total[5m])",
     "legendFormat": "{{resource}}-{{result}}"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "description": "Number of events handled by the controller",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(apisix_ingress_controller_events_total[5m])",
     "legendFormat": "{{resource}}-{{operation}}"
    }
   ]
  },
  {
   "title": "Cluster Health Check",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(apisix_ingress_controller_check_cluster_health_total[5m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Response Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(apisix_ingress_controller_apisix_bad_status_codes{status_code =~ \"[4-5].*\"}[$__range])) / sum(increase(apisix_ingress_controller_apisix_bad_status_codes[$__range]))"
    }
   ]
  },
  { "title": "Apisix Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "apisix_ingress_controller_apisix_requests",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apisix_ingress_controller_apisix_bad_status_codes",
     "legendFormat": "{{resource}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests Latencies",
   "type": "graph",
   "description": "Request latencies with APISIX",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(\n      apisix_ingress_controller_apisix_request_latencies_sum{}[1m]\n)) / sum (\n  rate(\n      apisix_ingress_controller_apisix_request_latencies_count{}[1m]\n  )\n)",
     "legendFormat": "average"
    }
   ]
  }
 ]
}