apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ingress-controller
  namespace: cloud
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: apisix-ingress-controller
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        app: apisix-ingress-controller
        tier: backend
    spec:
      hostNetwork: true
      containers:
      - envFrom:
        - configMapRef:
            name: cloud-config
        image: ???/???/ingress-controller:???
        imagePullPolicy: IfNotPresent
        name: ingress-controller
        ports:
        - containerPort: 8080
          hostPort: 8080
      terminationGracePeriodSeconds: 60
