name: lint-ci
on:
  push:
    branches:
      - master
      - kv/ci
  pull_request:
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golang-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
          args: --skip-files _test\.go